### PR TITLE
DBT blank page fix

### PR DESCRIPTION
**Pull request by sarithapillai8**

### CODE REVIEW

**Comment by avaidyam** [comment]
@sarithapillai8 Could you let me know why we are removing `allow-same-origin` from the `iframe sandbox`? It doesn't seem like this should affect anything inside the sandboxed view.

**Comment by sarithapillai8** [comment]
@avaidyam We were getting blank page with console issue - VM126 about:srcdoc:2 Uncaught DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'about:srcdoc' cannot be created in a document with origin 'http://localhost:3001' and URL 'about:srcdoc'.
    at d (about:srcdoc:2:171391)
    at Module.210 (about:srcdoc:3:17687)
    at l (about:srcdoc:1:952)
    at t (about:srcdoc:1:821)
    at Array.r [as push] (about:srcdoc:1:684)
    at about:srcdoc:3:120
    for the DBT activity. This change was added recently. For this this fix was done. Is there any issue?

**Comment by avaidyam** [comment]
@sarithapillai8 This sounds incorrect or backwards. If I understood the error correctly, it should NOT be possible for the embedded activity to change the URL of the parent (the LAMP UI).

**Comment by avaidyam** [comment]
@sarithapillai8 Closing this after discussion with @michaelmenon on this PR.

**Pull request closed without merging**
