### PR TITLE
Language settings to embedded activity

### PR DESCRIPTION
**Pull request by sarithapillai8**

### CODE REVIEW

**Comment by avaidyam** [comment]
@sarithapillai8 Can you adjust this to send to the embedded activity as a different variable, called `configuration`? This will conflict with if an `Activity.settings` actually has a parameter named `language`. As an example, it should look like this: 
```json
"configuration": {
    "language": "en-US"
}
```
In the future, we can add new configuration parameters as needed that will be sent by the UI code to the Activity code.

**Comment by sarithapillai8** [comment]
"configuration": {
    "language": "en-US"
} -  By this -  do you mean separate key for settings and configuration? or can we just concat a separate key to the data passing to the activity without changing the activity settings object?

**Comment by avaidyam** [comment]
@sarithapillai8 Yes, the `configuration` object is separate from the `settings` object. It is not going to be part of the `Activity`, as it is handled by the UI code.

**Comment by sarithapillai8** [comment]
Ok so we are passing a single JSON object through the postMessage function. 
So can I pass it like
 {settings: activity,settings, configuration:{language:"lang-val"}} ?

**Comment by avaidyam** [comment]
@sarithapillai8 Yes - that's exactly it! 
**Setup** (`LAMP-dashboard` prepares the embedded activity)
```typescript
let activity = ...
//  the below should contain the base64 string for the activity code or a URL to the base64 string that has the activity code
let spec_html = (await LAMP.ActivitySpec.view(activity.spec)).executable
let currentLanguageCode = ...
let startTimestamp = new Date().getTime()
```
**Input** (`LAMP-dashboard` uses `postMessage` to initialize after loading `spec_html` into an `iframe`)
```json
{
  "settings": activity.settings,
  "configuration": {
    "language": currentLanguageCode
  }
}
```
**Output** (`LAMP-activities` use `postMessage` to end activity session)
```json
{
  "data": ...,
  "temporal_slices": ...
}
```
**Result** (`LAMP-dashboard` uses API to upload to `LAMP-server`)
```typescript
let response = ... // from listener; see above
let endTimestamp = new Date().getTime()
await LAMP.ActivityEvent.create(participant_id, {
  "timestamp": startTimestamp,
  "activity": activity.id,
  "duration": endTimestamp - startTimestamp, 
  "static_data": response.data,
  "temporal_slices": response.temporal_slices
})
```

Hope this makes sense for a more complete picture of the `EmbeddedActivity` (that uses `ActivitySpec`, `Activity`, and `ActivityEvent` APIs) system.

**Pull request merged**
